### ISSUE TITLE
CMake support

### ISSUE THREAD

**Issue by slawekwaga** [JackoboLeChocobo/DeSmuME-Reloaded#3]
If the goal is to have cross platform support, CMake support would be nice. 
From cmake you can generate vsproj files, gnu makefiles and XCode projects for mac

**Comment by JackoboLeChocobo** [comment]
My github project is obsolote : all my projects and forks are now on Gitlab : https://gitlab.com/JackoboLeChocobo/ - Desmume-Reloaded : https://gitlab.com/JackoboLeChocobo/OpenLibrary-Desmume-Reloaded

GCC/G++/Make is used on Linux and MinGW / MSYS2 is used on Windows.
I don"t have a Mac computer and I will never get it because of the price accessibility...
So I will not maintain a support for this. And CMake is not an universal solution for compilation of the projects. Stop about this please.
